export const SIGNUP_USER_SUCCESS = "SIGNUP_USER_SUCCESS";
export const SIGNUP_ERROR = "SIGNUP_ERROR";
export const CREATE_TRIP = 'CREATE_TRIP';
export const CREATE_TRIP_ERROR = 'CREATE_TRIP_ERROR';
export const VIEW_TRIPS = 'VIEW_TRIPS'
export const VIEW_TRIPS_ERROR = 'VIEW_TRIPS_ERROR'
export const DELETE_TRIPS = "DELETE_TRIPS"
